# -*- coding: utf-8 -*-
"""24.11.Директории.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qSNVWmt1MtGWAxGkHDeE-hzAXl50N6TW
"""

# Задача 4 Только файлы
import os
def get_paths(path = '.'):
  for name in os.listdir(path):
    abs_path = os.path.abspath(os.path.join(path,name))
    if os.path.isfile(abs_path) is True:
      yield abs_path

    elif os.path.isdir(abs_path) is True:
      yield from get_paths(abs_path)

get_paths('test1')

for i in get_paths('test1'):
  print(i)

# Задача 3 И папки и файлы
import os
def get_paths(path = '.'):
  for name in os.listdir(path):
    abs_path = os.path.abspath(os.path.join(path,name))

    yield abs_path

    if os.path.isdir(abs_path) is True:
      yield from get_paths(abs_path)

get_paths('test1')

for i in get_paths('test1'):
  print(i)